#include"Engine.hpp"

CreateInstance createInstance;
ValidationLayers validationLayers;
CreateSurface createSurface;
PickPhysicalDevice pickPhysicalDevice;
CreateLogicalDevice createLogicalDevice;
SwapChain swapChain;
CreateImageViews createImageViews;
CreateRenderPass createRenderPass;
CreateDescriptorSetLayout createDescriptorSetLayout;
CreateGraphicsPipeline createGraphicsPipeline;
CreateCommandPool createCommandPool;
CreateResources createResources;
CreateFrameBuffers createFrameBuffers;
CreateTexture createTexture;
LoadModel loadModel;
CreateBuffer createBuffer;
CreateDescriptorSets createDescriptorSets;
CreateCommandBuffer createCommandBuffer;
CreateSyncObjects createSyncObjects;